version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - staticcheck
  settings:
    staticcheck:
      checks:
        - "all"
        - "-QF*"
        - "-ST1000"
